name: my workflow

on:
    push:
        branches:
            - 'v[0-9]+\.+[0-9]+'

jobs:
    my_first_ci:
        runs-on: ubuntu-latest

        steps:
        - name: check out
          id: check_out
          uses: actions/checkout@v4

        - name: scanning
          id: scanning
          uses: aquasecurity/trivy-action@master
          with:
            scan-type: 'fs'
            severity: 'HIGH'
            format: 'table'
            output: 'trivy-result.txt'

        - name: send to slack
          id: send_to_slack
          uses: slackapi/slack-github-action@v1.24.0
          with: 
            payload: |
                {
                    "text":"Zz",
                    "blocks": [
                        {
                            "type": "section",
                            "text":{
                                "type": "mrkdwn",
                                "text": "Zz"
                            }
                        }
                    ]
                }
          env: 
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
            SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

        - name: upload trivy result
          id: upload_trivy_result
          uses: MeilCli/slack-upload-file@v3
          with: 
            slack_token: ${{ secrets.SLACK_TOKEN }}
            channel_id: ${{ secrets.SLACK_CHANNEL_ID }}
            content: 'file content'
            file_type: 'text'
            file_name: 'trivy-result.txt'
            title: 'scan result'
            initial_comment: 'post by Zz'



