name: my workflow

on:
    push:
        branches:
            - 'v[0-9]+\.+[0-9]+'

jobs:
    my_first_ci:
        runs-on: ubuntu-latest

        if: '!startsWith(github.event.head_commit.message, ' #NORUN')'

        steps:
        - name: check out
          id: check_out
          uses: actions/checkout@v4

        - name: scanning
          id: scanning
          uses: aquasecurity/trivy-action@master
          with:
            scan-type: 'fs'
            severity: 'HIGH'
            format: 'table'
            output: 'trivy-result.txt'

        - name: send to slack
          id: send_to_slack
          uses: rtCamp/action-slack-notify@v2
          env: 
            SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
            SLACK_TITLE: 'Scan failed'
            SLACK_MESSAGE: |
                Failed trivy scan, see uploaded report
                <mailtohttps://www.google.com/|hiuijuijijjjuoju>

        - name: upload trivy result
          id: upload_trivy_result
          uses: MeilCli/slack-upload-file@v3
          with: 
            slack_token: ${{ secrets.SLACK_TOKEN }}
            channel_id: ${{ secrets.SLACK_CHANNEL_ID }}
            file_path: 'trivy-result.txt'
            title: 'scan result'
            initial_comment: 'post by Zz'



