name: my workflow

on:
    push

jobs:
    my_first_ci:
        runs-on: ubuntu-lastest

        steps:
        - name: check out code
          id: check_out_code
          uses: actions/checkout@v4
          
          


