name: my workflow

on:
    push:
        branches:
            - 'v[0-9]+\.+[0-9]+'

jobs:
    my_first_ci:
        runs-on: ubuntu-lastest

        steps:
        - name: check out
          id: check_out
          uses: actions/checkout@v4

        - name: scanning
          id: scanning
          uses: aquasecurity/trivy-action@master
          with:
            scan-type: 'fs'
            input: .
            severity: 'HIGH'
            format: table

        - name: send to slack
          id: send_to_slack
          uses: slackapi/slack-github-action@v1.24.0
          with:
            payload: |
                {
                "text": "failed"
                }
          env: 
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
            SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK


